language: haskell
ghc:
  - 7.6
before_install:
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update -qq
  - sudo apt-get --no-install-recommends install libgtksourceview-3.0-dev libwebkitgtk-3.0-dev
install:
  - cabal install Cabal
  - cabal install gtk2hs-buildtools
  - cabal install --only-dependencies --enable-tests
script:
  - cabal configure -fexamples && cabal build